# ReAct Agent Template
name: gpt_4o_mini_react
version: 0.0.1
type: react
description: A react agent capable of code interpreter
module_name: infiagent.agent.react
class_name: AsyncReactAgent
target_tasks:
  - code interpreter
llm:
  model_name: gpt-4o-mini
  module_name: infiagent.llm
  class_name: OpenAIGPTClient
  params:
    temperature: 0.0
    top_p: 0.9
    repetition_penalty: 1.0
    max_tokens: 1024
prompt_template: !prompt ZeroShotReactPromptWithPrint
plugins:
  - name: python_code_sandbox
    type: tool
    config: configs/tool_configs/async_python_code_sandbox_docker.yaml